######################################################################
# Automatically generated by qmake (3.0) Thu Apr 10 11:36:01 2014
######################################################################

QT += widgets

TEMPLATE = app
TARGET = frak
INCLUDEPATH += .

# Input
HEADERS += frakablak.h frakszal.h
SOURCES += frakablak.cpp frakszal.cpp main.cpp

